config/routes.rb
TicketSearch::Application.routes.draw do
  match "/teams" => "teams#create"
  put "/searches" => "searches#update"
  resources :teams do
    resources :games
  end
  resources :searches, :only => [:new, :show, :update]
  get '/token_input', :to => "searches#token_input"
  get '/searches', :to => 'searches#show'
  match "/tickets/next", :to => 'tickets#next'
  root :to => 'searches#new'


end

app/models/search.rb
class Search < ActiveRecord::Base
  attr_accessor :team, :date_start, :date_end, :price_min, :price_max
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    @search = Search.new
  end
  
  def token_input
    @teams = Team.where("teams.name LIKE ?", "%#{params[:q].split(' ').map{|word| word[0].upcase + word[1..-1]}.join(' ')}%" )
    respond_to do |format|
      format.json { render :json => @teams.collect{ |team| {:id => team[:id], :name => team[:name] }}.to_json }
    end
  end
  
  def show
    if params[:search][:team].empty?
      redirect_to :back
      flash[:error] = "Sorry, we couldn't find that team..."
      return
    end
    @search = Search.new
    @team = Team.find(params[:search][:team])  
    @price_min = 1
    @total_tickets = 0
    @games = []
    @team.games.order("date").limit(8).each{|game| @games << game if game.number_of_tickets > 5 }
    @price_max = 5000  
    @number = 1
    price_data = []
    dates = []
    rating_data = []
    @games.each do |game|
        dates << game[:date].strftime("%b %-d")    
        price_data << {y: game.average_price.to_i, marker: {symbol: "url(assets/small_icons/#{game[:opponent].split(' ')[-1]}_40x40.png)"}}
        rating_data << { y: game[:game_rating].to_i, marker: {symbol: "url(assets/small_icons/#{game[:opponent].split(' ')[-1]}_40x40.png)"}}
    end
    @line = @team.price_chart(price_data, rating_data, dates)
    respond_to do |format|
      format.html
    end   
  end

  def update
      @date_start = params[:search][:date_start] == "" ? Date.current.strftime("%m-%d-%Y") : params[:search][:date_start]
      @date_end = params[:search][:date_end] == "" ? (Date.current + 30).strftime("%m-%d-%Y") : params[:search][:date_end]
      @price_min = params[:search][:price_min].to_i
      @price_max = params[:search][:price_max].to_i      
      @team = Team.find_by_name(params[:search][:team])
      @number = 1
      filtered_games = @team.filtered_games(@date_start, @date_end)
      @games = filtered_games[:games]
      @total_tickets = filtered_games[:total_tickets]
      price_data = []
      dates = []
      rating_data = []
      @games.each do |game|
        total_tickets = game.number_of_tickets
        if total_tickets < 3 
          @games.delete(game)
        else
          dates << game[:date].strftime("%b %-d")    
          price_data << {y: game.average_price.to_i, marker: {symbol: "url(assets/small_icons/#{game[:opponent].split(' ')[-1]}_40x40.png)"}}
          rating_data << { y: game[:game_rating].to_i, marker: {symbol: "url(assets/small_icons/#{game[:opponent].split(' ')[-1]}_40x40.png)"}}
        end
      end
      @line = @team.price_chart(price_data, rating_data, dates) 
      respond_to do |format|
        format.js
      end
  end

end

app/helpers/searches_helper.rb
module SearchesHelper    
  def check_overall_rating(overall_rating)
    return ["game_tickets green span12", "green_score"] if overall_rating >= 65 
    return ["game_tickets yellow span12", "yellow_score"] if overall_rating < 65 && overall_rating >= 50
    return ["game_tickets red span12", "red_score"] if overall_rating < 50
  end

  
  def game_price_chart(game_id)
    LazyHighCharts::HighChart.new('graph') do |f|
        prices_array = $redis.zrange "game:average_price_over_time:#{game_id}", 0, -1, withscores: true
        graph_data = prices_array.sort {|x,y| DateTime.parse(x[0]).to_f <=> DateTime.parse(y[0]).to_f }
        categories = []
        interval = prices_array.length/3 + 1
        graph_data.each_with_index do |prices, i|
          if i % interval == 0 
            categories << Date.parse(prices[0]).strftime("%-m/%d")
          else
            categories << ""
          end
        end
        f.chart!(:backgroundColor => 'transparent')
        f.title(:style=>{:color => 'transparent'})
        f.credits!({:enabled => false})
        f.legend(:enabled => false)
        f.tooltip!(:enabled => true)
        f.series(:name => 'Average Ticket Price', :type => 'line', :data => graph_data, :marker => {:enabled => false}, :lineWidth => 4, :lineColor => "#8197B0")
        f.xAxis!({:labels => {:style => {:fontSize => 16, :fontWeight => 'bold'}}, :offset => 10, :lineWidth => 0, :categories => categories})
        f.yAxis!({:labels => {:style => {:fontSize => 16, :fontWeight => 'bold'}, :formatter => "function(){return '$' + this.value}".js_code}, :title => {:text => false}, })
    end
  end

  
  def ticket_summary(game, section)
    game_id = game[:id]
    ticket = @game_data[:best_ticket]
    team = game.team
    team_id = team[:id]
    average_game_price = game.average_price.to_i
    min_game_price_array =  $redis.zrange "tickets_for_game_by_price:#{game_id}", 0, 0, withscores: true
    max_game_price_array =  $redis.zrange "tickets_for_game_by_price:#{game_id}", -1, -1, withscores: true
    min_game_price = min_game_price_array[0][1].to_i
    max_game_price = max_game_price_array[0][1].to_i
    number_tickets = game.number_of_tickets
    opponent_object = game.opponent_object
    opp_stars_array = opponent_object.stars
    section_name = section[:name].split(' ').map!{|word| word[0].upcase + word[1..-1]}.join(" ")
    average_section_price = section[:average_price]
    number_of_sections = $redis.zcard "sections_for_team_by_average_price:#{team_id}"
    section_rank = $redis.zrevrank "sections_for_team_by_average_price:#{team_id}", section[:id]
    ticket_price_rank = $redis.zrank "tickets_for_game_by_price:#{game_id}", ticket['stub_hub_id']
    
    # gen_stats_header = "General Stats: "
    gen_stats_0 = raw("<td>Listings: </td><td>#{number_tickets}</td>")
    gen_stats_1 = raw("<td>Min Price: </td><td>$#{min_game_price}</td>")
    gen_stats_2 = raw("<td>Max Price: </td><td>$#{max_game_price}</td>")
    gen_stats_3 = raw("<td>Average Price: </td><td>$#{average_game_price}</td>")
  
    # opp_score_header = "Game Score: #{@game_data[:game_rating]}"
    game_score_0 = raw("<td>Opponent Name: </td><td>#{opponent_object[:name]}</td>")
    game_score_1 = raw("<td>Record: </td><td>#{opponent_object[:record]}</td>")
    overall_star_rating = 0
    game_score_3 = raw("<td>Star Players: </td>")
    stars_list = ""
    if opp_stars_array.length == 0
      stars_list += "<td>none</td>"
    else   
      stars_list += "<td>"
      opp_stars_array.each do |star|
        stars_list += "#{star[:name]}, "
        overall_star_rating += (star[:rating].to_f * 4)
        overall_star_rating = 100 if overall_star_rating > 100
      end 
      stars_list = stars_list[0...-2]
      stars_list += "</td>"
    end
    game_score_3 = game_score_3 + raw(stars_list)
    game_score_4 = raw("<td>Star Rating: </td><td>#{overall_star_rating.to_i}</td>")

    ticket_score_0 = raw("<td>Expected Ticket Price: </td><td>$#{average_section_price}</td>")
    ticket_score_1 = raw("<td>Actual Ticket Price: </td><td>$#{ticket['price']}</td>")
    ticket_score_2 = raw("<td>Section: </td><td>#{section_name}</td>")
    ticket_score_3 = raw("<td>Section Rank: </td><td>#{section_rank}/#{number_of_sections}</td>")
    
    
   return [gen_stats_0, gen_stats_1, gen_stats_2, gen_stats_3, 
          game_score_0, game_score_1, game_score_3, game_score_4,
          ticket_score_0, ticket_score_1, ticket_score_2, ticket_score_3]
    
  end
end

app/views/searches/_next.html.erb
<% price_min = @price_min %>
<% price_max = @price_max %>
<% number = @number %>
<% game = @game %>
<% game_data = game.view_game_data(price_min, price_max, number) %>
<% section = Section.find(game_data[:best_ticket]['section_id']) %>
<% if game_data.is_a? Hash %>
	<div class="span12" id="<%= game[:id] %>">
		<div class="flip-container">
			<div class="flipper">
				<div class="<%= check_overall_rating(game_data[:overall_rating])[0] %> front">
					<div class ="row">
						<div class="flip_button_div span1">
							<a class="btn flip_button" href="#"><i class="icon-info-sign"></i></a>
						</div>	
						<h2 class = "span10" style="color: grey">
							<%= game[:date] %>
						</h2>
						<div class= "seat_view_div span1">
							<%= link_to(image_tag('binoculars.png', :width => '20px', :height => '20px'), '#', :class => "popover-with-html", :title => "<b>Seat View</b>", "data-placement" => "bottom", "data-content" => "#{image_tag(section[:seat_view_url], :width => '400px', :height => '300px', :class => 'img-rounded')}") %>
						</div>
					</div>
					<div class="row" style="text-align:center">
						<%= image_tag "team_logos/#{game[:opponent].split(' ')[-1]}.png", :class => "img-rounded", :style=>"height: 200px; width: auto;" %>
					</div>
					<div class="row" style="margin-top: 10%;">
						<div class= "span11 offset1">
							<%=image_tag "ticket_icon/game_rating.ico", :class => "img-rounded span3", :style => "max-width: 24%; max-height: 10%" %> 
							<div class="span3" style="font-size: 35px; font-weight: bold; margin-top: 8%; margin-left: -5%; color: grey">
								<%= game_data[:game_rating] %>
							</div>
							<%=image_tag "ticket_icon/seat_rating.ico", :class => "img-rounded span3", :style=>"max-width: 24%; max-height: 10%;"%> 
							<div class="span3" style="font-size: 35px; font-weight: bold; margin-top: 8%; margin-left: -2%; color: grey">
								<%= game_data[:seat_rating] %>
							</div>
						</div>
					</div>
					<div class="row" style="margin-bottom: 5%">
						<div class="span12">
							<div class="span3">
								<%= button_to "", tickets_next_path(:game => game[:id], :price_min => price_min, :price_max => price_max, :number => number-2, :next => false), :remote => true, :controller => 'tickets', :class=>"previous_button span12" %>
							</div>
							<div class="<%= check_overall_rating(game_data[:overall_rating])[1] %> span6" style="font-size: 50px; padding: 50px 40px 50px 40px; border-radius: 50%; text-align: center"> 
								<%= game_data[:overall_rating] %>
							</div>
							<div class="span3">
								<%= button_to "", tickets_next_path(:game => game[:id], :price_min => price_min, :price_max => price_max, :number => number, :next => true), :remote => true, :controller => 'tickets', :class=>"next_button span12" %>
							</div>
						</div>
					</div>

					<table class="table">
						<tr class = "row">
							<td><%= section[:name].scan(/\d{1,3}/)[-1] %></td>
							<td><%= game_data[:best_ticket]['row'] %></td>
							<td><%= game_data[:best_ticket]['quantity']%></td>
							<td>$<%= game_data[:best_ticket]['price']%></td>
						</tr>
						<tr class="row">
							<td>SEC</td>
							<td>ROW</td>
							<td>AVAIL</td>
							<td>PRICE</td>
						</tr>
					</table>

					<li class = "span11">
						<%= link_to "Purchase Ticket", game_data[:best_ticket]['url'], :target => 'blank', :class => "btn btn-large btn-block btn-inverse", :style => "margin-top: 5px;" %>
					</li>
				</div>
				<div class="<%= check_overall_rating(game_data[:overall_rating])[0] %> back">
					<div class="flip_button_div span1">
						<a class="btn flip_button" href="#"><i class="icon-info-sign"></i></a>
					</div>
					<h3 class="span11"> Ticket Summary </h3>
					<div class="span12" style="text-align: left; padding-right: 5%">
						<% ticket_summary = ticket_summary(game, game_data, section) %>
						<p><%= ticket_summary[0] %></p>
						<p><%= ticket_summary[1] %></p>
						<p><%= ticket_summary[2] %></p>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/searches/_show.html.erb
<div class="inner span10 offset1" style= "padding: 10px;">
	<div class="span12">
		<div class="span12">
			<h1 style="font-size: 50px; padding: 10px;"><%= @team[:name] %></h1>
		</div>

		<div class="row">
			<div class = "team_info span6">
				<%= render :partial => 'team_info', :locals => {:team => @team } %>
			</div>
			<div class = "search_form_div span6" >
				<h4>Refine Your Search: </h4>
				<%= form_for @search, :method => 'put', :remote => true, :html => {:class => "form-search refine_search_form"} do |f| %>
				<div class="control-group">
					<div class="controls">
						<%= f.text_field :team, :placeholder => @team[:name], :class => "input-search span12", :style => "height: 50px; font-size: 25px; line-height: 25px;" %>
					</div>
				</div>
				<div class="control-group">
					<div class="control"s>
						<%= f.hidden_field :price_min, :id => "price_min" %>
						<%= f.hidden_field :price_max, :id => "price_max" %>
						<%= f.text_field :date_start, :class => 'input span5 datepicker', :placeholder => "Start Date", :style =>"margin-right: 10px;" %>
						<%= f.text_field :date_end, :class => 'input span5 datepicker', :placeholder => "End Date"%>
					</div>
				</div>
				<div class="control-group">
					<div class="controls">
						<label id="slider_div">
							<div class = "slider"></div>
							<div id="amount_min"></div>
							<div id="amount_max"></div>
						</label>
					</div>
				</div>
				<div class="control-group">
					<div class="controls">
						<%= f.submit "Find Tickets", :class => 'btn' %>
						<% end %>
						<div class="progress">
							<div class="bar" style="width: 0%;"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<%= render :partial => 'update', :locals => {:team => @team, :total_tickets => @total_tickets, :date_start => @date_start, :date_end => @date_end, :price_min => @price_min, :price_max => @price_max, :games => @games} %>
		</div>
	</div>
</div>

app/views/searches/_team_info.html.erb
<% number_of_games = @games.length %>
<%=javascript_tag "changeSpan()" %>
<% if number_of_games >= 10 && number_of_games < 15 %>
	<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" %>
	<%=javascript_tag "$('#line_chart').css('min-width', '1500px')" %>
	
<% elsif number_of_games >= 15 %>
	<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" %>		
	<%=javascript_tag "$('#line_chart').css('min-width', '2000px')" %>
<% end %>


<div id="price_chart" class="span12" style="padding-right: 2%;">
	<div id="line_chart_div" class="row-fluid span12" style="overflow-x:scroll; overflow-y: hidden; position: relative;">
		<div id="line_chart" style="position: absolute; top: -15%; left: -5%; height: 120%; min-width: 1000px;" >
			<%= high_chart("line_chart", @line) %>
		</div>
	</div>
</div>

app/views/searches/_ticket.html.erb
<% section = Section.find(@game_data[:best_ticket]['section_id'])%>
<% seat_view_url = section[:seat_view_url] %>

<div class ="seat_view_image" id="<%= @game[:id]%>_seat_view_button_photo" style="display: none; width: 300px; height: 168px; position: absolute; z-index: 1000">
	<%=image_tag(seat_view_url, :class => 'img', :style => 'height: 100%; width: 100%') %>	
	<div class="arrow-down">		
	</div>
</div>

<div class="flip-container" style="display:none">
	<div class="flipper">
		<div class="<%= check_overall_rating(@game_data[:overall_rating])[0] %> front">
			<div class ="ticket_header row-fluid" style="">
				<div class="flip_button_div span2">
					<a class="flip_button icon-info-sign card-icon" href="#" style="font-size: 240%;"></a>
				</div>	
				<div class = "span8" style="font-size: 200%; color: #666464; margin-top: 1%; text-align: center">
					<%= @game[:date].strftime("%-m-%-d-%Y") %>
				</div>
				<div class= "seat_view_div span2">
					<%= link_to "", '#', :class => "seat_view_button icon-eye-open card-icon", :id => "#{@game[:id]}_seat_view_button", :style => "font-size: 240%" unless seat_view_url == "f" %>
				</div>

			</div>
			<div class="opponent_logo row-fluid" style=" margin-top: 10%; text-align: center">
				<%= image_tag "team_logos/#{@game[:opponent].split(' ')[-1]}.png", :class => "img-rounded", :style=>"height: 120px; width: auto;" %>
			</div>
			<div class="middle">
				<div class="row-fluid span12" style="margin-top: 5%; margin-left: 2%; margin-bottom: 10%; text-align: center">
					<div class="span3 card-score">
						Game Score:
					</div>
					<div class="span3" style="font-size: 200%; font-weight: bold; margin-top: 8%; color: #666464">
						<%= @game_data[:game_rating] %>
					</div>
					<div class="span3 card-score">
						Seat Score:
					</div>
					<div class="span3" style="font-size: 200%; font-weight: bold; margin-top: 8%; color: #666464">
						<%= @game_data[:seat_rating] %>
					</div>

				</div>
				<div class="row-fluid">
					<div class="span12" style="text-align: center">
						<div class="span3 icon-arrow-left card-icon" style="font-size: 300%; height: 40px; overflow: hidden">
							<%= button_to "", tickets_next_path(:game => game[:id], :price_min => @price_min, :price_max => @price_max, :number => @number-2, :next => false), :remote => true, :controller => 'tickets', :class=>"previous_button span12" %>
						</div>
						<div class="<%= check_overall_rating(game_data[:overall_rating])[1] %> span6" style="font-size: 400%; text-align: center"> 
							<%= @game_data[:overall_rating] %>
						</div>
						<div class="span3 icon-arrow-right card-icon" style="font-size: 300%; height: 40px; overflow: hidden">
							<%= button_to "", tickets_next_path(:game => @game[:id], :price_min => @price_min, :price_max => @price_max, :number => @number, :next => true), :remote => true, :controller => 'tickets', :class=>"next_button span12" %>
						</div>
					</div>
				</div>
			</div>

			<table class="table table-condensed" style = "font-size: 100%; margin-bottom: 4%; width: 100%">
				<tr class="row">
					<td><%= section[:name].scan(/\d{1,3}/)[-1] %></td>
					<td><%= @game_data[:best_ticket]['row'] %></td>
					<td><%= @game_data[:best_ticket]['quantity']%></td>
					<td>$<%= @game_data[:best_ticket]['price']%></td>
				</tr>
				<tr class="row" style="text-align: center">
					<td>SEC</td>
					<td>ROW</td>
					<td>AVAIL</td>
					<td>PRICE</td>
				</tr>
			</table>
			<div class="row-fluid">
				<div class = "span12">
					<%= link_to "Purchase Ticket", @game_data[:best_ticket]['url'], :target => 'blank', :class => "btn btn-large btn-block btn-inverse" %>
				</div>
			</div>

		</div>
		<div class="<%= check_overall_rating(@game_data[:overall_rating])[0] %> back" style="margin-left: -1%;">
			<div class="flip_button_div row-fluid ticket_header">
				<div class="span1">
					<a class="flip_button icon-info-sign card-icon" href="#" style="font-size: 240%;"></a>
				</div>
				<div class = "span11" style="font-size: 200%; color: #666464; margin-top: 1%; text-align: center">
					Ticket Details 
				</div>
			</div>
			<div style="overflow-y: scroll; overflow-x: hidden; height: 83%">			
				<div class="span12">
					<% ticket_summary = ticket_summary(@game, section ) %>
					<table class="table" style="font-size: 14pt">
						<thead>
							<h2 style="font-size: 20pt; text-align: left">Game Stats:</h2>
						</thead>
						<tbody>
							<tr><%= ticket_summary[0] %></tr>
							<tr><%= ticket_summary[1] %></tr>
							<tr><%= ticket_summary[2] %></tr>
							<tr><%= ticket_summary[3] %></tr>
						</tbody>
					</table>
					<table class="table" style="font-size: 14pt">
						<thead>
							<h2 style="font-size: 20pt; text-align: left">Game Score: <%= @game_data[:game_rating] %></h2>
						</thead>
						<tbody>
							<tr><%= ticket_summary[4] %></tr>
							<tr><%= ticket_summary[5] %></tr>
							<tr><%= ticket_summary[6] %></tr>
							<tr><%= ticket_summary[7] %></tr>
						</tbody>
					</table>
					<table class="table" style="font-size: 14pt">
						<thead>
							<h2 style="font-size: 20pt; text-align: left">Seat Score: <%= @game_data[:seat_rating] %></h2
						</thead>
						<tbody>
							<tr><%= ticket_summary[8] %></tr>
							<tr><%= ticket_summary[9] %></tr>
							<tr><%= ticket_summary[10] %></tr>
							<tr><%= ticket_summary[11] %></tr>
						</tbody>
					</table>
					<h2 style="font-size: 20pt; text-align: left">Average Price Trend:</h2>
					<div id="average_price_time<%= @game[:id] %>" class ="highchart_div" style="height: 250px;">
						<%= high_chart("average_price_time#{@game[:id]}", game_price_chart(@game[:id])) %>
					</div>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/searches/_update.html.erb
<div class="update_tickets_loader_div">
	<div class="loader_div">
		Updating Tickets...
	</div>
	<%= image_tag "ajax-loader.gif", :style=> "margin-left: -10%" %>
</div>
<% counter = 0 %>
<% if @games.length == 0 %>
	<h1 style="color: #C13B36; background:transparent"> Sorry, no tickets were found </h1>
<% else %>
	<div class="row-fluid">
	<% @games.each do |game|  %>
		<% @game = game %>
		<% @game_data = @game.view_game_data(@price_min, @price_max, @number) %>
		<% if @game_data %>
			<% unless @game_data[:best_ticket]['section_id'].nil? %>
				<% counter += 1 %>
				<div class="ticket_spacer span3" style="margin-left: 0%; margin-right: 0%;">			
					<div id="<%= @game[:id]%>" class="ticket_partial_div span10">
							<%= render :partial => "ticket", :locals => {:game => @game, :game_data => @game_data, :price_min => @price_min, :price_max => @price_max, :number => @number} %>				
					</div>	
				</div>	
			<% end %>
		<% end %>
	<% end %>
	</div>
	
	<% if counter == 0 %>
		<h1 style="color: #C13B36"> Sorry, no games were found </h1>
	<% end %>
<% end %>

app/views/searches/new.html.erb
<div class="primary_logo row-fluid span12" style="font-size: 650%; margin-top: 5%; margin-bottom: 5%; text-align: center; color: #FF4A56; background: transparent; text-shadow: 2px 2px black;">
	TICKETBRAINS<small style= "color: #9CB6CB; font-size: 60%; font-family: sans-serif; font-weight: bold" >beta</small>
</div>
<div class="new_search">
	<div class="row-fluid">
		<div class="new_search_div">
			<div class="span10 offset2">
			<%= form_for @search, :method => 'get', :html => {:class => "form-search", :ready => 'false'} do |f| %>
				<div class="span9" style="margin-top: 10%">
					<%= f.text_field :team, :placeholder => "Enter a Team Name to Begin", :class => "span12 search", :style => "height: 42px; font-size: 30px; line-height: 42px;" %>
					<%= f.submit "Find Tickets!", :class => "btn-large btn-inverse update_team_button", :style => "visibility: block; margin-top: 5%" %>
				<% end %>
				</div>
			</div>		
		</div>
		<div class="row-fluid span12">
			<div class="explanation_div span12" style="margin-bottom: 5%; margin-top: 5%">
				<h1 style= "color: #4B474B; background: transparent">Why Ticketbrains? </h1>
				<div class="explanation_text_top span12">
						<div class="span4">
							<h4>Buying Tickets For Sporting Events Sucks.</h3>
							Everyone wants a good deal, but none of the major ticket marketplaces share any useful pricing data with their users.
						</div>
						<div class="span4">
							<h4>Big Data</h4>
							We analyze thousands of tickets per event, do all the math we know you don't want to do, and provide you with the best deals.
						</div>
						<div class="span4">
							<h4>We're Sports Fans</h4>
							We actually take into account the quality of the game before determining a ticket's true value
						</div>
				</div>
				<div class="explanation_text_bottom span12">
						<div class="span6">
							<h4>Our Algorithm Works</h4> 
							We filter out absurdly priced tickets that skew other services' data...  Our average ticket prices reflect  tickets that actually have a shot at being sold... not the tickets worth $20 dollars that are being listed for $2,000 on other websites.
						</div>
						<div class="span6">
							<h4>Its Free!</h4>
							All of our listings provide links to trusted ticket resellers such as Stubhub, and we charge no additional fees.
						</div>
				</div>
				<!-- <div class="explanation_disclaimer">
							<p>NOTE: Ticketbrains currently only provides listings for NBA games, but other leagues and events will be supported in the near future.</p> -->
				</div>
			</div>
		</div>
	</div>
</div>

app/views/searches/seat_view.js.erb
$('#'+ "<%= @link_id %>").popover({
        placement : 'bottom', //placement of the popover. also can use top, bottom, left or right
        title : '<div style="text-align:center; color:red; text-decoration:underline; font-size:14px;"> Muah ha ha</div>', //this is the top title bar of the popover. add some basic css
        html: 'true', //needed to show html of course
        content : '"<%= image_tag @seat_view_image, :width => "200px", :height => "200px", :class => "img-rounded" %>"'
  });

app/views/searches/show.js.erb
$(document).ready(function(){
	$('#outer').css('background', 'url("/backgrounds/<%= @team[:name].split(' ')[-1] %>_background.jpg")');
});

app/views/searches/update.js.erb
$('#team_info_partial').html("<%= j(render :partial => 'team_info', :locals => {:line => @line }) %>");
$('.results_tickets').html("<%= j(render :partial => 'update', :locals => {:team => @team, :total_tickets => @total_tickets, :date_start => @date_start, :date_end => @date_end, :price_min => @price_min, :price_max => @price_max, :games => @games, :number => @number}) %>");
ticketFadeIn();
setTimeout(function (){
	colorBorders();
	flipper();
	seatView();
}, 500);

$(window).resize(function(){
	changeSpan();
});